<form action="agregarSub" method="POST" class="mb-3">
    <label class="form-label">subscripcion</label>
    <input type="text" name="subscripcion" class="form-control">
    <label class="form-label">Categoria</label>
    <input type="text" name="categoria" class="form-control">
    <label class="form-label">Precio</label>
    <input type="number" name="precio" class="form-control">
    <label class="form-label">caracteristicas</label>
    <input type="text" name="caracteristicas" class="form-control">
    <label class="form-label">duracion</label>
    <input type="number" name="duracion" class="form-control">
    <label class="form-label">nombre</label>
    <input type="text" name="nombre" class="form-control">
    <input type="submit" class="btn btn-primary">
</form>
<a class="btn btn-primary" href="volver">Volver</a>