<form action="iniciar" method="POST" class="mx-5">
  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="email">
  </div>
  <div class="mb-3">
    <label class="form-label">contraseña</label>
    <input type="password" class="form-control" name="contraseña">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<h2><a href="registro">Registrarse</a></h2>