<?php include_once 'Templates/header.phtml';?>

<table class='table'>
<thead>
  <tr>
    <th scope='col'>SUSCRIPCION</th>
    <th scope='col'>BENEFICIOS</th>
    <th scope='col'>PRECIO</th>
    <th scope='col'>DURACION(AÑOS)</th>
  </tr>
</thead>
<tbody>
<?php
foreach ($subscripciones as $subscripcion):?>
    <tr>
      <td> <?php echo $subscripcion->nombre_subscripcion ?></td>
      <td> <?php echo $subscripcion->caracteristicas ?></td>
      <td> <?php echo $subscripcion->precio ?> $USD</td>
      <td> <?php echo $subscripcion->duracion ?></td>
    </tr>
    <?php endforeach ?>
    </tbody></table>
