<!DOCTYPE html>
<html>
<nav class="">
    <ul class="">
        <li class="nav-item p-2"><a class="nav-link" href="agregar">Agregar producto</a></li>
        <li class="nav-item p-2"><a class="nav-link" href="modificar">Modificar producto</a></li>
        <li class="nav-item p-2"><a class="nav-link" href="eliminar">Eliminar producto</a></li>
        <li class="nav-item p-2"><a class="nav-link" href="agregarCategoria">Agregar categoria</a></li>
        <li class="nav-item p-2"><a class="nav-link" href="eliminarCategoria">Eliminar categoria</a></li>
        <li class="nav-item p-2"><a class="nav-link" href="modificarCategorias">Modificar categoria</a></li>
    </ul>
</nav>

</html>